### ISSUE TITLE
Is it possible to stream video from memory?

### ISSUE THREAD

**Issue by dme-compunet** [mysteryx93/LibMpv-OpenGL#2]
Hi @mysteryx93! A fabulous job!

I don't know the api of mpv, and I see that loading a video is via `LoadFile', but I want to stream a video directly from memory, is there such an option?

**Comment by mysteryx93** [comment]
The documentation is here
https://mpv.io/manual/master/#command-interface-loadlist-%3Curl%3E-%5B%3Cflags%3E%5D

> Load the given file or URL and play it. Technically, this is just a playlist manipulation command (which either replaces the playlist or appends an entry to it). Actual file loading happens independently. For example, a loadfile command that replaces the current file with a new one returns before the current file is stopped, and the new file even begins loading.
> 
> Second argument:
> 
> <replace> (default)
> Stop playback of the current file, and play the new file immediately.
> <append>
> Append the file to the playlist.
> <append-play>
> Append the file, and if nothing is currently playing, start playback. (Always starts with the added file, even if the playlist was not empty before running this command.)
> The third argument is a list of options and values which should be set while the file is playing. It is of the form opt1=value1,opt2=value2,... When using the client API, this can be a MPV_FORMAT_NODE_MAP (or a Lua table), however the values themselves must be strings currently. These options are set during playback, and restored to the previous value at end of playback (see [Per-File Options](https://mpv.io/manual/master/#per-file-options)).

You can do streaming via a URL. Perhaps you can do streaming via a file, or even a "fake" file that maps to memory?

**Comment by dme-compunet** [comment]
Could you please elaborate or refer me to examples of how to do it, I'm trying using a URL and it doesn't work:

```csharp
var video = ...

using var listener = new HttpListener();
listener.Prefixes.Add($"http://localhost:8888/mpv_test");
listener.Start();

while (true)
{
    var context = listener.GetContext();

    using var response = context.Response;
    response.AppendHeader("Content-Range", $"bytes={0}-{video.Length}/{video.Length}");

    response.OutputStream.Write(video);

    Console.WriteLine(context.Request.Headers.ToString());
}
```

and runs like this:

```
mpv http://localhost:8888
```

I also tried with Pipe and failed:

```
mpv pipe://localhost/mpv_test
```

Can you explain to me how to do it?
Thenks!

**Comment by mysteryx93** [comment]
Video streaming is a whole other topic. I don't know whether it supports raw video files, or internet streaming protocols, or both.

Trying to implement a video streaming protocol manually can be a serious project. I cannot help you here.

Maybe take a step back; what are you trying to accomplish exactly?

**Comment by dme-compunet** [comment]
> Maybe take a step back; what are you trying to accomplish exactly?

I develop DRM software in Avalonia and I don't want to save the video to a file, because then it will be possible to access it, I'm looking for functionality like `MediaPlayer` in WinUI that allows playing video from Stream object source.

Thank you for your help!

**Comment by mysteryx93** [comment]
I don't know how much development you want to put into it.

The options I see off the top of my head.

1. Create a virtual web server to provide the video feed

2. Create a fake file that maps to memory (there's a project for that, don't remember the name; but probably requires installing special drivers in the OS)

3. Use VapourSynth, particularly if you need to do extra video processing. Here I created a viewer for VapourSynth video scripts. It's in WPF and not updated for Avalonia though.
https://github.com/mysteryx93/VapourSynthViewer.NET

Will remain the problem: how to get your video input into it. If there are no existing solution that work, you can create your own VideoSource filter that reads the stream from memory, in C++. Then would remain the issue of audio playback to figure out. That option would be a lot more work but would be possible for advanced use-case. You could then add any kind of live video processing you want.

**Comment by mysteryx93** [comment]
Probably simple media streaming is the best option for you.

This came after a very quick search. There are ready-made media server tools to publish your video.
https://github.com/bluenviron/mediamtx

**Comment by dme-compunet** [comment]
In the end I used with `mpv_stream_cb_add_ro()` with a custom protocol, as described here:
[https://github.com/mpv-player/mpv/blob/master/libmpv/stream_cb.h](https://github.com/mpv-player/mpv/blob/master/libmpv/stream_cb.h)
