### ISSUE TITLE
How to use in WPF

### ISSUE THREAD

**Issue by zcyc** [mysteryx93/LibMpv-OpenGL#3]

**Comment by mysteryx93** [comment]
If you use WPF, you only need to care about Windows, which works best in NativeView rendering

You just need to port this View to WPF
https://github.com/mysteryx93/LibMpv-OpenGL/blob/main/Src/LibMpv.Avalonia/NativeView.cs

You can also look at this other library that has WPF sample with NativeView implementation; but it doesn't support MPV v2 API
https://github.com/hudec117/Mpv.NET-lib-

**Comment by zcyc** [comment]
Thank you.
